linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  disable:
    # deprecated linters
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # disabled due to personal preference
    - depguard
    - exhaustruct
    - gomnd
    - nlreturn
    - tagliatelle
    - unparam
    - wrapcheck
    - wsl
    # disabled because of generics. https://github.com/golangci/golangci-lint/issues/2649
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    # TODO: re-evaluate following linters:
    - gci
    - gochecknoglobals # high false-positive rate
    - gochecknoinits
    - goconst
    - gocritic
    - goerr113
    - gofumpt
    - gosec
    - inamedparam
    - ireturn
    - lll
    - nonamedreturns
    - paralleltest
    - perfsprint
    - protogetter
    - revive
    - stylecheck
    - tagalign
    - testifylint
    - testpackage
    - unparam
    - varnamelen

linters-settings:
  cyclop:
    max-complexity: 15
  funlen:
    lines: 100
  gci:
    sections:
      - standard
      - blank
      - default
      - blank
      - prefix(github.com/sapslaj/)
      - blank
      - dot
    custom-order: true

issues:
  exclude:
    - Line contains TODO/BUG/FIXME # godox
    - Profiling endpoint is automatically exposed # gosec
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - funlen
        - maintidx
        - forcetypeassert
        - govet # TODO
        - goconst
    - path: lokiclient/
      linters:
        - usestdlibvars
        - testpackage
        - predeclared
        - tparallel
        - nakedret
        - funlen
        - containedctx
        - gocognit
        - errcheck
        - errorlint
        - gofmt
        - whitespace
        - gocyclo
        - cyclop
        - goimports
        - dupl
        - godot
    - path: config/config\.go
      linters:
        - gocognit
        - cyclop
        - dupl
    - path: destination/elasticsearch_destination\.go
      linters:
        - errchkjson
        - usestdlibvars
    - path: destination/prometheus_destination\.go
      linters:
        - cyclop
        - nestif
        - promlinter
    - path: destination/stdout_destination\.go
      linters:
        - unconvert
    - path: enricher/maxminddb_enricher\.go
      linters:
        - govet # TODO
        - forcetypeassert
        - promlinter
        - nestif
        - funlen
        - gocognit
        - cyclop
        - gocyclo
        - gochecknoinits
    - path: enricher/netdb_enricher\.go
      linters:
        - nestif
        - funlen
        - gocognit
        - cyclop
    - path: enricher/rdns_enricher\.go
      linters:
        - promlinter
        - forcetypeassert
    - path: server/server.go
      linters:
        - gosec # TODO
    - path: syncmap/syncmap\.go
      linters:
        - dupword
        - forcetypeassert
    - path: transport/transport\.go
      linters:
        - exhaustive # TODO
        - promlinter
        - funlen
        - errcheck
        - cyclop
    - path: main\.go
      linters:
        - cyclop
        - errcheck
