linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  disable:
    - depguard # TODO
    - exhaustruct # TODO
    - gci # TODO
    - gochecknoglobals # high false-positive rate
    - gochecknoinits # TODO
    - goconst # TODO
    - gocritic # TODO
    - goerr113 # TODO
    - gofumpt # TODO
    - gomnd # TODO
    - gosec # TODO
    - inamedparam # TODO
    - ireturn # TODO
    - lll # TODO
    - nlreturn # TODO
    - nonamedreturns # TODO
    - paralleltest # TODO
    - perfsprint # TODO
    - protogetter # TODO
    - revive # TODO
    - rowserrcheck # disabled because of generics. https://github.com/golangci/golangci-lint/issues/2649
    - stylecheck # TODO
    - tagalign # TODO
    - tagliatelle # disabled because we explicitly do not want this
    - testifylint # TODO
    - testpackage # TODO
    - unparam # TODO
    - varnamelen # TODO
    - wastedassign # disabled because of generics. https://github.com/golangci/golangci-lint/issues/2649
    - wrapcheck # TODO
    - wsl # TODO


linters-settings:
  cyclop:
    max-complexity: 15
  funlen:
    lines: 100

issues:
  exclude:
    - Line contains TODO/BUG/FIXME # godox
    - Profiling endpoint is automatically exposed # gosec
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - funlen
        - maintidx
        - forcetypeassert
        - govet # TODO
        - goconst
    - path: lokiclient/
      linters:
        - usestdlibvars
        - testpackage
        - predeclared
        - tparallel
        - nakedret
        - funlen
        - containedctx
        - gocognit
        - errcheck
        - errorlint
        - gofmt
        - whitespace
        - gocyclo
        - cyclop
        - goimports
        - dupl
        - godot
    - path: config/config\.go
      linters:
        - gocognit
        - cyclop
    - path: destination/elasticsearch_destination\.go
      linters:
        - errchkjson
        - usestdlibvars
    - path: destination/prometheus_destination\.go
      linters:
        - cyclop
        - nestif
        - promlinter
    - path: destination/stdout_destination\.go
      linters:
        - unconvert
    - path: enricher/maxminddb_enricher\.go
      linters:
        - govet # TODO
        - forcetypeassert
        - promlinter
        - nestif
        - funlen
        - gocognit
        - cyclop
        - gocyclo
        - gochecknoinits
    - path: enricher/rdns_enricher\.go
      linters:
        - promlinter
        - forcetypeassert
    - path: server/server.go
      linters:
        - gosec # TODO
    - path: syncmap/syncmap\.go
      linters:
        - dupword
        - forcetypeassert
    - path: transport/transport\.go
      linters:
        - exhaustive # TODO
        - promlinter
        - funlen
        - errcheck
        - cyclop
    - path: main\.go
      linters:
        - cyclop
        - errcheck
