version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal:host-gateway
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/prometheus
        cat <<EOF > /etc/prometheus/prometheus.yml
        global:
          scrape_interval: 15s
          evaluation_interval: 15s
        scrape_configs:
          - job_name: prometheus
            static_configs:
              - targets: [prometheus:9090]
          - job_name: morbius
            static_configs:
              - targets: [host.docker.internal:6060]
        EOF
        /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus
  loki:
    image: grafana/loki:2.6.1
    ports:
      - 3100:3100
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/loki/local-config.yaml
        auth_enabled: false
        server:
          http_listen_port: 3100
        schema_config:
          configs:
            - from: 2020-10-24
              store: boltdb-shipper
              object_store: filesystem
              schema: v11
              index:
                prefix: index_
                period: 24h
        limits_config:
          max_query_series: 100000
          ingestion_rate_mb: 1024
          ingestion_burst_size_mb: 1024
          per_stream_rate_limit: 512M
          per_stream_rate_limit_burst: 1024M
        common:
          path_prefix: /loki
          storage:
            filesystem:
              chunks_directory: /loki/chunks
              rules_directory: /loki/rules
          replication_factor: 1
          ring:
            kvstore:
              store: inmemory
        analytics:
          reporting_enabled: false
        EOF
        /usr/bin/loki -config.file=/etc/loki/local-config.yaml

  phlare:
    image: grafana/phlare:latest
    ports:
      - 4100:4100
    user: 0:0
    extra_hosts:
      - host.docker.internal:host-gateway
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/phlare
        cat <<EOF > /etc/phlare/config.yaml
        scrape_configs:
          - job_name: phlare
            scrape_interval: 15s
            static_configs:
              - targets: [phlare:4100]
          - job_name: morbius
            scrape_interval: 15s
            static_configs:
              - targets: [host.docker.internal:6060]
        EOF
        /usr/bin/phlare -config.file=/etc/phlare/config.yaml

  grafana:
    image: grafana/grafana:main
    ports:
      - 3000:3000
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_FEATURE_TOGGLES_ENABLE: flameGraph
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Elasticsearch
            type: elasticsearch
            uid: P31C819B24CF3C3C7
            access: proxy
            url: http://elasticsearch:9200
            database: netflow
            jsonData:
              esVersion: 8.0.0
              timeField: timestamp
          - name: Loki
            type: loki
            uid: P8E80F9AEF21F6940
            access: proxy
            url: http://loki:3100
            jsonData:
              httpHeaderName1: "X-Scope-OrgID"
            secureJsonData:
              httpHeaderValue1: "tenant1"
          - name: Phlare
            type: phlare
            uid: PD3452FC02DB93657
            access: proxy
            basicAuth: false
            url: http://phlare:4100
            version: 1
          - name: Prometheus
            type: prometheus
            uid: PBFA97CFB590B2093
            access: proxy
            url: http://prometheus:9090
        EOF
        /run.sh

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      cluster.routing.allocation.disk.threshold_enabled: 'false'
      ES_JAVA_OPTS: -Xms2g -Xmx2g
    mem_limit: 4g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      INTERACTIVESETUP_ENABLED: 'false'
